
import { Subject, Chapter } from './types';

export const GRADES = [6, 7, 8, 9, 10, 11, 12];

export const CHAPTERS: Record<number, Partial<Record<Subject, Chapter[]>>> = {
    6: {
        [Subject.Science]: [
            { id: 'sci6-1', name: 'Components of Food' },
            { id: 'sci6-2', name: 'Sorting Materials into Groups' },
            { id: 'sci6-3', name: 'Separation of Substances' },
            { id: 'sci6-4', name: 'Getting to Know Plants' },
            { id: 'sci6-5', name: 'Body Movements' },
            { id: 'sci6-6', name: 'The Living Organisms — Characteristics and Habitats' },
            { id: 'sci6-7', name: 'Motion and Measurement of Distances' },
            { id: 'sci6-8', name: 'Light, Shadows and Reflections' },
            { id: 'sci6-9', name: 'Electricity and Circuits' },
            { id: 'sci6-10', name: 'Fun with Magnets' },
            { id: 'sci6-11', name: 'Air Around Us' },
        ],
        [Subject.Mathematics]: [
            { id: 'math6-1', name: 'Knowing Our Numbers' },
            { id: 'math6-2', name: 'Whole Numbers' },
            { id: 'math6-3', name: 'Playing with Numbers' },
            { id: 'math6-4', name: 'Basic Geometrical Ideas' },
            { id: 'math6-5', name: 'Understanding Elementary Shapes' },
            { id: 'math6-6', name: 'Integers' },
            { id: 'math6-7', name: 'Fractions' },
            { id: 'math6-8', name: 'Decimals' },
            { id: 'math6-9', name: 'Data Handling' },
            { id: 'math6-10', name: 'Mensuration' },
            { id: 'math6-11', name: 'Algebra' },
            { id: 'math6-12', name: 'Ratio and Proportion' },
        ],
        [Subject.English]: [
            { id: 'eng6-1', name: 'Who Did Patrick’s Homework?' },
            { id: 'eng6-2', name: 'How the Dog Found Himself a New Master!' },
            { id: 'eng6-3', name: 'Taro’s Reward' },
            { id: 'eng6-4', name: 'An Indian-American Woman in Space: Kalpana Chawla' },
        ],
    },
    7: {
        [Subject.Science]: [
            { id: 'sci7-1', name: 'Nutrition in Plants' },
            { id: 'sci7-2', name: 'Nutrition in Animals' },
            { id: 'sci7-3', name: 'Heat' },
            { id: 'sci7-4', name: 'Acids, Bases and Salts' },
            { id: 'sci7-5', name: 'Physical and Chemical Changes' },
            { id: 'sci7-6', name: 'Respiration in Organisms' },
            { id: 'sci7-7', name: 'Transportation in Animals and Plants' },
            { id: 'sci7-8', name: 'Reproduction in Plants' },
            { id: 'sci7-9', name: 'Motion and Time' },
            { id: 'sci7-10', name: 'Electric Current and its Effects' },
            { id: 'sci7-11', name: 'Light' },
            { id: 'sci7-12', name: 'Forests: Our Lifeline' },
            { id: 'sci7-13', name: 'Wastewater Story' },
        ],
        [Subject.Mathematics]: [
            { id: 'math7-1', name: 'Integers' },
            { id: 'math7-2', name: 'Fractions and Decimals' },
            { id: 'math7-3', name: 'Data Handling' },
            { id: 'math7-4', name: 'Simple Equations' },
            { id: 'math7-5', name: 'Lines and Angles' },
            { id: 'math7-6', name: 'The Triangle and its Properties' },
            { id: 'math7-7', name: 'Comparing Quantities' },
            { id: 'math7-8', name: 'Rational Numbers' },
            { id: 'math7-9', name: 'Perimeter and Area' },
            { id: 'math7-10', name: 'Algebraic Expressions' },
            { id: 'math7-11', name: 'Exponents and Powers' },
            { id: 'math7-12', name: 'Visualising Solid Shapes' },
        ],
    },
    8: {
        [Subject.Science]: [
            { id: 'sci8-1', name: 'Crop Production and Management' },
            { id: 'sci8-2', name: 'Microorganisms: Friend and Foe' },
            { id: 'sci8-3', name: 'Coal and Petroleum' },
            { id: 'sci8-4', name: 'Combustion and Flame' },
            { id: 'sci8-5', name: 'Conservation of Plants and Animals' },
            { id: 'sci8-6', name: 'Reproduction in Animals' },
            { id: 'sci8-7', name: 'Reaching the Age of Adolescence' },
            { id: 'sci8-8', name: 'Force and Pressure' },
            { id: 'sci8-9', name: 'Friction' },
            { id: 'sci8-10', name: 'Sound' },
            { id: 'sci8-11', name: 'Chemical Effects of Electric Current' },
            { id: 'sci8-12', name: 'Some Natural Phenomena' },
            { id: 'sci8-13', name: 'Light' },
        ],
        [Subject.Mathematics]: [
            { id: 'math8-1', name: 'Rational Numbers' },
            { id: 'math8-2', name: 'Linear Equations in One Variable' },
            { id: 'math8-3', name: 'Understanding Quadrilaterals' },
            { id: 'math8-4', name: 'Data Handling' },
            { id: 'math8-5', name: 'Squares and Square Roots' },
            { id: 'math8-6', name: 'Cubes and Cube Roots' },
            { id: 'math8-7', name: 'Comparing Quantities' },
            { id: 'math8-8', name: 'Algebraic Expressions and Identities' },
            { id: 'math8-9', name: 'Mensuration' },
            { id: 'math8-10', name: 'Exponents and Powers' },
            { id: 'math8-11', name: 'Direct and Inverse Proportions' },
            { id: 'math8-12', name: 'Factorisation' },
            { id: 'math8-13', name: 'Introduction to Graphs' },
        ],
    },
    9: {
        [Subject.Science]: [
            { id: 'sci9-1', name: 'Matter in Our Surroundings' },
            { id: 'sci9-2', name: 'Is Matter Around Us Pure' },
            { id: 'sci9-3', name: 'Atoms and Molecules' },
            { id: 'sci9-4', name: 'Structure of the Atom' },
            { id: 'sci9-5', name: 'The Fundamental Unit of Life' },
            { id: 'sci9-6', name: 'Tissues' },
            { id: 'sci9-7', name: 'Motion' },
            { id: 'sci9-8', name: 'Force and Laws of Motion' },
            { id: 'sci9-9', name: 'Gravitation' },
            { id: 'sci9-10', name: 'Work and Energy' },
            { id: 'sci9-11', name: 'Sound' },
            { id: 'sci9-12', name: 'Improvement in Food Resources' },
        ],
        [Subject.Mathematics]: [
            { id: 'math9-1', name: 'Number Systems' },
            { id: 'math9-2', name: 'Polynomials' },
            { id: 'math9-3', name: 'Coordinate Geometry' },
            { id: 'math9-4', name: 'Linear Equations in Two Variables' },
            { id: 'math9-5', name: 'Introduction to Euclid’s Geometry' },
            { id: 'math9-6', name: 'Lines and Angles' },
            { id: 'math9-7', name: 'Triangles' },
            { id: 'math9-8', name: 'Quadrilaterals' },
            { id: 'math9-9', name: 'Circles' },
            { id: 'math9-10', name: 'Heron’s Formula' },
            { id: 'math9-11', name: 'Surface Areas and Volumes' },
            { id: 'math9-12', name: 'Statistics' },
        ],
    },
    10: {
        [Subject.Physics]: [
            { id: 'phy10-1', name: 'Light – Reflection and Refraction' },
            { id: 'phy10-2', name: 'Human Eye and Colourful World' },
            { id: 'phy10-3', name: 'Electricity' },
            { id: 'phy10-4', name: 'Magnetic Effects of Electric Current' },
        ],
        [Subject.Chemistry]: [
            { id: 'chem10-1', name: 'Chemical Reactions and Equations' },
            { id: 'chem10-2', name: 'Acids, Bases and Salts' },
            { id: 'chem10-3', name: 'Metals and Non-metals' },
            { id: 'chem10-4', name: 'Carbon and its Compounds' },
        ],
        [Subject.Biology]: [
            { id: 'bio10-1', name: 'Life Processes' },
            { id: 'bio10-2', name: 'Control and Coordination' },
            { id: 'bio10-3', name: 'How do Organisms Reproduce?' },
            { id: 'bio10-4', name: 'Heredity' },
            { id: 'bio10-5', name: 'Our Environment' },
        ],
        [Subject.Mathematics]: [
            { id: 'math10-1', name: 'Real Numbers' },
            { id: 'math10-2', name: 'Polynomials' },
            { id: 'math10-3', name: 'Pair of Linear Equations in Two Variables' },
            { id: 'math10-4', name: 'Quadratic Equations' },
            { id: 'math10-5', name: 'Arithmetic Progressions' },
            { id: 'math10-6', name: 'Triangles' },
            { id: 'math10-7', name: 'Coordinate Geometry' },
            { id: 'math10-8', name: 'Introduction to Trigonometry' },
            { id: 'math10-9', name: 'Some Applications of Trigonometry' },
            { id: 'math10-10', name: 'Circles' },
            { id: 'math10-11', name: 'Areas Related to Circles' },
            { id: 'math10-12', name: 'Surface Areas and Volumes' },
            { id: 'math10-13', name: 'Statistics' },
            { id: 'math10-14', name: 'Probability' },
        ],
    },
    11: {
        [Subject.Physics]: [
            { id: 'phy11-1', name: 'Units and Measurements' },
            { id: 'phy11-2', name: 'Motion in a Straight Line' },
            { id: 'phy11-3', name: 'Motion in a Plane' },
            { id: 'phy11-4', name: 'Laws of Motion' },
            { id: 'phy11-5', name: 'Work, Energy and Power' },
            { id: 'phy11-6', name: 'System of Particles and Rotational Motion' },
            { id: 'phy11-7', name: 'Gravitation' },
            { id: 'phy11-8', name: 'Mechanical Properties of Solids' },
            { id: 'phy11-9', name: 'Mechanical Properties of Fluids' },
            { id: 'phy11-10', name: 'Thermal Properties of Matter' },
            { id: 'phy11-11', name: 'Thermodynamics' },
            { id: 'phy11-12', name: 'Kinetic Theory' },
            { id: 'phy11-13', name: 'Oscillations' },
            { id: 'phy11-14', name: 'Waves' },
        ],
        [Subject.Chemistry]: [
            { id: 'chem11-1', name: 'Some Basic Concepts of Chemistry' },
            { id: 'chem11-2', name: 'Structure of Atom' },
            { id: 'chem11-3', name: 'Classification of Elements and Periodicity in Properties' },
            { id: 'chem11-4', name: 'Chemical Bonding and Molecular Structure' },
            { id: 'chem11-5', name: 'Thermodynamics' },
            { id: 'chem11-6', name: 'Equilibrium' },
            { id: 'chem11-7', name: 'Redox Reactions' },
            { id: 'chem11-8', name: 'Organic Chemistry – Some Basic Principles and Techniques' },
            { id: 'chem11-9', name: 'Hydrocarbons' },
        ],
        [Subject.Biology]: [
            { id: 'bio11-1', name: 'The Living World' },
            { id: 'bio11-2', name: 'Biological Classification' },
            { id: 'bio11-3', name: 'Plant Kingdom' },
            { id: 'bio11-4', name: 'Animal Kingdom' },
            { id: 'bio11-5', name: 'Morphology of Flowering Plants' },
            { id: 'bio11-6', name: 'Anatomy of Flowering Plants' },
            { id: 'bio11-7', name: 'Structural Organisation in Animals' },
            { id: 'bio11-8', name: 'Cell: The Unit of Life' },
            { id: 'bio11-9', name: 'Biomolecules' },
            { id: 'bio11-10', name: 'Cell Cycle and Cell Division' },
            { id: 'bio11-11', name: 'Photosynthesis in Higher Plants' },
            { id: 'bio11-12', name: 'Respiration in Plants' },
            { id: 'bio11-13', name: 'Plant Growth and Development' },
            { id: 'bio11-14', name: 'Breathing and Exchange of Gases' },
            { id: 'bio11-15', name: 'Body Fluids and Circulation' },
            { id: 'bio11-16', name: 'Excretory Products and their Elimination' },
            { id: 'bio11-17', name: 'Locomotion and Movement' },
            { id: 'bio11-18', name: 'Neural Control and Coordination' },
            { id: 'bio11-19', name: 'Chemical Coordination and Integration' },
        ],
        [Subject.Mathematics]: [
            { id: 'math11-1', name: 'Sets' },
            { id: 'math11-2', name: 'Relations and Functions' },
            { id: 'math11-3', name: 'Trigonometric Functions' },
            { id: 'math11-4', name: 'Complex Numbers and Quadratic Equations' },
            { id: 'math11-5', name: 'Linear Inequalities' },
            { id: 'math11-6', name: 'Permutations and Combinations' },
            { id: 'math11-7', name: 'Binomial Theorem' },
            { id: 'math11-8', name: 'Sequences and Series' },
            { id: 'math11-9', name: 'Straight Lines' },
            { id: 'math11-10', name: 'Conic Sections' },
            { id: 'math11-11', name: 'Introduction to Three Dimensional Geometry' },
            { id: 'math11-12', name: 'Limits and Derivatives' },
            { id: 'math11-13', name: 'Statistics' },
            { id: 'math11-14', name: 'Probability' },
        ],
    },
    12: {
        [Subject.Physics]: [
            { id: 'phy12-1', name: 'Electric Charges and Fields' },
            { id: 'phy12-2', name: 'Electrostatic Potential and Capacitance' },
            { id: 'phy12-3', name: 'Current Electricity' },
            { id: 'phy12-4', name: 'Moving Charges and Magnetism' },
            { id: 'phy12-5', name: 'Magnetism and Matter' },
            { id: 'phy12-6', name: 'Electromagnetic Induction' },
            { id: 'phy12-7', name: 'Alternating Current' },
            { id: 'phy12-8', name: 'Electromagnetic Waves' },
            { id: 'phy12-9', name: 'Ray Optics and Optical Instruments' },
            { id: 'phy12-10', name: 'Wave Optics' },
            { id: 'phy12-11', name: 'Dual Nature of Radiation and Matter' },
            { id: 'phy12-12', name: 'Atoms' },
            { id: 'phy12-13', name: 'Nuclei' },
            { id: 'phy12-14', name: 'Semiconductor Electronics: Materials, Devices and Simple Circuits' },
        ],
        [Subject.Chemistry]: [
            { id: 'chem12-1', name: 'Solutions' },
            { id: 'chem12-2', name: 'Electrochemistry' },
            { id: 'chem12-3', name: 'Chemical Kinetics' },
            { id: 'chem12-4', name: 'The d-and f-Block Elements' },
            { id: 'chem12-5', name: 'Coordination Compounds' },
            { id: 'chem12-6', name: 'Haloalkanes and Haloarenes' },
            { id: 'chem12-7', name: 'Alcohols, Phenols and Ethers' },
            { id: 'chem12-8', name: 'Aldehydes, Ketones and Carboxylic Acids' },
            { id: 'chem12-9', name: 'Amines' },
            { id: 'chem12-10', name: 'Biomolecules' },
        ],
        [Subject.Biology]: [
            { id: 'bio12-1', name: 'Sexual Reproduction in Flowering Plants' },
            { id: 'bio12-2', name: 'Human Reproduction' },
            { id: 'bio12-3', name: 'Reproductive Health' },
            { id: 'bio12-4', name: 'Principles of Inheritance and Variation' },
            { id: 'bio12-5', name: 'Molecular Basis of Inheritance' },
            { id: 'bio12-6', name: 'Evolution' },
            { id: 'bio12-7', name: 'Human Health and Disease' },
            { id: 'bio12-8', name: 'Microbes in Human Welfare' },
            { id: 'bio12-9', name: 'Biotechnology: Principles and Processes' },
            { id: 'bio12-10', name: 'Biotechnology and its Applications' },
            { id: 'bio12-11', name: 'Organisms and Populations' },
            { id: 'bio12-12', name: 'Ecosystem' },
            { id: 'bio12-13', name: 'Biodiversity and Conservation' },
        ],
        [Subject.Mathematics]: [
            { id: 'math12-1', name: 'Relations and Functions' },
            { id: 'math12-2', name: 'Inverse Trigonometric Functions' },
            { id: 'math12-3', name: 'Matrices' },
            { id: 'math12-4', name: 'Determinants' },
            { id: 'math12-5', name: 'Continuity and Differentiability' },
            { id: 'math12-6', name: 'Application of Derivatives' },
            { id: 'math12-7', name: 'Integrals' },
            { id: 'math12-8', name: 'Application of Integrals' },
            { id: 'math12-9', name: 'Differential Equations' },
            { id: 'math12-10', name: 'Vector Algebra' },
            { id: 'math12-11', name: 'Three Dimensional Geometry' },
            { id: 'math12-12', name: 'Linear Programming' },
            { id: 'math12-13', name: 'Probability' },
        ],
    },
};
